### ISSUE TITLE
As a developer, I want to have the model of a poll represented in the backend of my application (Estimation: 13)

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#10]
AC:
- Database entity exists
- REST API for CRUD Operations on this entity exists

_Hint_
- Don't think to far in advance when it comes to designing the schema of the entity, as later migrations will handle later extension of functionality

**Comment by essal0815** [comment]
**As a lecturer, I can start a poll.
Single/multiple choice can be specified
Number of options can be specified (named A, B, C, ...)
No two polls can be running at the same time
As a student, I can anonymously participate in a poll that is taking place.
As a lecturer, I can end a poll that I have previously started.
As a lecturer, I can see the poll results once the poll is closed.**

**Comment by essal0815** [comment]
Estimation: 13
