### ISSUE TITLE
As a lecturer or a student, i want to be able to upload links, as if they were files (Estimation 3)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#125]
Dep: #122

AC:
- [ ] The DB model should support a file's content to be either an actual file stored in the DB, OR to be a hyperlink. Not both!

_Hint: It does not matter, if the link is not supported (anymore). Supposedly, the model contains info about wether the "file" actually contains a file, or a link._

**Comment by adrianjost** [comment]
Idea: Define `contenttype: 'url'` and handle it different than other contenttypes. the stored data can than be the url

**Comment by essal0815** [comment]
Pure Backend story.
