### ISSUE TITLE
As a lecturer and as a student, I want to have my authorship and a timestamp associated to a file that i am uploading (Estimation 3)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#153]
DEP: #83

AC:
- [ ] Any file will have an association to the uploaders account
- [ ] it can be determined wether a file belongs to a student or to a lecturer 
- [x] Any file will have an time stamp of the upload time association to it

**Comment by essal0815** [comment]
Backend
