### ISSUE TITLE
As a lecturer or as a student, i want to see all materials associated to a course in the course overview - grouped into materials uploaded by students and materials uploaded by lecturers

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#155]
DEP: #154 

AC:
- [x] In the course overview, there is a box containing a scrollable list of all materials that were uploaded from lecturers, and another scrollable box, that contains a list of all materials from students
- [x] Clicking on the title of a material will "open" it directly (download / open in browser if link)
- [x] Authorship of the file is not provided by the list

_Hint: Use the [course overview mock](https://www.figma.com/file/6yo4FXp2lLtE4uZvI0lsFr/Paper-Prototype?node-id=135%3A8) if you want_

**Comment by adrianjost** [comment]
My working time for this week is unforunatly already over, but I have started implementing the files view so there is only logic and tests missing.

![image](https://user-images.githubusercontent.com/22987140/72219609-49c84300-3548-11ea-9104-0c1da13f8658.png)

Branch: https://github.com/hpi-swt2/lecture-portal/tree/feature/%23155-course-file-view
