### ISSUE TITLE
As a lecturer i want to able to add and remove files to a specific lecture of a course i am managing (Estimation 8)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#158]
DEP: #153

AC: 
- [ ] In the lecture settings view - and that ALSO means in the lecture creation view (since they are the same) - is a section "materials" 
- [ ] In this section is a list of all materials associated to this particular lecture
- [ ] Clicking on a file's name will automatically open (download / open in browser if link) the file
- [ ] There is a button / text "delete file" besides every file, that when clicked promts a window titled "Are you sure you want to remove this file?", a "Yes" and a "No" option.
- [ ] Clicking "Yes" removes the file entirely from the lecture, course and the DB, and closes the window
- [ ] Clicking "No" Closes the window as well
- [ ] There is a button "Add lecture material" in the section through wich the lecturer can add and upload new material to the lecture
- [ ] Adding /uploading anew file will automatically fill out all information about the file in the db
- [ ] A student will NEVER be able to upload, nor to delete materials that are associated to a specific LECTURE

_Hint: use the [mockup](https://www.figma.com/file/6yo4FXp2lLtE4uZvI0lsFr/Paper-Prototype?node-id=135%3A1019) if you want_

**Comment by essal0815** [comment]
Adding file design not specified.

**Comment by MartinBuessemeyer** [comment]
Please look at @WorldofJARcraft 's Branch: feature/#125-upload-links. Maybe you should use this branch as the base for this Issue in order to not do everything twice.
