### ISSUE TITLE
As a a lecturer, and a student, i want a list of all lecture material in my lectures dashboard (Estimation 3)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#159]
DEP: #158 

AC:
- [ ] The lectures and the students dashboard both contain a section called "Lecture materials"
- [ ] This section holds a scrollable list of all files associated to this particular lecture
- [ ] Clicking on a files name will "open" it (download if file / open link if link)

_Hint: You can use the [mockup](https://www.figma.com/file/6yo4FXp2lLtE4uZvI0lsFr/Paper-Prototype?node-id=135%3A1716) if you want. the students and the lecture dashboard do not differ in this matter._

**Comment by essal0815** [comment]
Icon should be there, but not file type specific
