### ISSUE TITLE
As a student, I want to be able to subscribe to a calendar feed, which delivers up to date calender events for all lectures of all courses I am enrolled in (13).

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#175]
*AC:*
- The calender-feed can be subscribed via url, which can be found in the account settings as it can be seen in the mock
- The calender feed updates according to changes the lecturer makes on his existing lectures in a course the student is enrolled in.
- The calender feed updates accordingly when new lectures are scheduled in a course the student is enrolled in.
- The calender feed - by default - does not add notifications to scheduled lectures.
- The calender feed titles the calender event with: Title Course - Title Lecture.

_Hint: 
https://www.figma.com/file/6yo4FXp2lLtE4uZvI0lsFr/Paper-Prototype?node-id=0%3A69 the students view contains the account view_

**Comment by simonstadlinger** [comment]
![image](https://user-images.githubusercontent.com/33035544/73090979-bbee3f80-3ed9-11ea-8ca3-d409201924b1.png)

I tried this out on my local instance and it failed with creating a user. @phoeinx @LucPrestin Could you please have a look at that.

**Comment by phoeinx** [comment]
@simonstadlinger everything fine now? Works fine on my machine
