### ISSUE TITLE
As a lecturer, I can create a new lecture (Estimation 8)

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#22]
**FROM THE LECTURERS VIEW**

- Clicking the ["Create Lecture" Button](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=32%3A14&scaling=min-zoom) initiates the creation of a new lecture instance by redericting the user to the [Create-Lecture page](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=25%3A194&scaling=min-zoom). 

- After submitting all required info for creating a lecture (title, an optional description, enable questions / polls) a new lecture is created

- Creating a lecture adds it to the lectures list of lectures (["My lectures"](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=32%3A14&scaling=min-zoom))

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by essal0815** [comment]
Lecture is bound to one lecturer.

Lecturer and Student Decision out of scope.

**Comment by adrianjost** [comment]
@MartinBuessemeyer here is some early review from the design-leads regarding the UX:
- [ ] the status should not be selectable by the user. This should all be triggered by actions like "start lecture", "stop lecture", ... Maybe you could use a hidden input or even better a database default value for that?
- [ ] the features checkboxes should all be enabled/checked by default

**Comment by adrianjost** [comment]
Work is done at: https://github.com/hpi-swt2/lecture-portal/tree/feature/%2322-lecturer-create-new-lecture

**Comment by adrianjost** [comment]
Open TODOs:
- [ ] each lecture should have a lecturer (user) assigned
