### ISSUE TITLE
As a student that has joined a course, I want to be able to review an archived lecture (of that course), no matter if i have joined it earlier or not.

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#234]
DEP: None
AC:
- [ ] When a student does not join a lecture, but is a course member, he can review all lectures that are in the "Archived" state

**Comment by WorldofJARcraft** [comment]
Was already implemented, but I added some tests and refactorings.

**Comment by Blatzheim** [comment]
Does not seem to work:

![Screenshot 2020-02-05 at 17 12 12 (2)](https://user-images.githubusercontent.com/49294088/73859756-d5c54600-483a-11ea-8648-59eba4be4e57.png)
