### ISSUE TITLE
As a German, I always want to use the standard timepicker with military time format in the lecture settings.

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#235]
DEP: None
AC:
- [ ] No matter in which environment, the time picker of the lecture settings always uses military time (24h)

**Comment by adrianjost** [comment]
Not possible to implement with HTML Standard.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
You need to setup your system correctly in the language you wan't to use.

**Comment by MartinBuessemeyer** [comment]
@adrianjost please look at this: https://stackoverflow.com/questions/32609407/html-input-time-in-24-format. Wouldn't be that sufficient?

**Comment by adrianjost** [comment]
yes we found that as well but if we would use this we would probably use some accessibility features and it is bad practice to work against browser settings that are there because the user has set up something in a way. Imagine there is an exchange student.

**Comment by MartinBuessemeyer** [comment]
ok I would say it is up to @Blatzheim to decide.

**Comment by adrianjost** [comment]
I agree. 
@Blatzheim also keep in mind that any 3. party picker may have issues on mobile devices as well.

**Comment by essal0815** [comment]
Just moved back because of kanban limits. According to github logs seems to be the latest added.

**Comment by adrianjost** [comment]
Nach Diskussion mit Alex soll der Timepicker so bleiben wie er ist, aber ein polyfill für Safari Desktop (und alle anderen Browser die den Type noch nicht kennen) eingerichtet werden.

**Comment by adrianjost** [comment]
Something like this would be a great fit: https://github.com/chemerisuk/better-timeinput-polyfill/blob/master/README.md
