### ISSUE TITLE
As a user i want visually uniform, and not skipped, headers so i can navigate quickly

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#238]
(Adrian the stage is yours)
DEP: None
AC:
- [x] When i scroll down any (!) page, no heading levels will be skipped 

_Hint: more info can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Accessibility_concerns), under "Accessibility concerns"._

**Comment by adrianjost** [comment]
![image](https://user-images.githubusercontent.com/22987140/73075849-293fa780-3ebd-11ea-904e-a7facc034723.png)

**Comment by Blatzheim** [comment]
Done if @adrianjost agrees.
