### ISSUE TITLE
As a student, I can join a lecture by clicking on it (Estimation 8)

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#24]
**FROM THE STUDENTS VIEW**

- From the "[current lecture's page"](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=36%3A216&scaling=min-zoom),  a student can join a lecture by clicking on "join" 

- Joining a lecture, assigns that student to the lectures **list of students**

- After joining a lecture, the student is presented with this lectures student dashboard (tbd)

- The process takes up to 30 s for first-time users.

- The process takes under 10 s for frequent users.

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by adrianjost** [comment]
Creating this page is in scope
