### ISSUE TITLE
Remove “Edit”-Button in Lecturer View of Lecture

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#242]
AC:
- [ ] Remove “Edit”-Button in Lecturer View of Lecture (we have the Settings bar for that)

**Comment by adrianjost** [comment]
Do you mean this button?
![image](https://user-images.githubusercontent.com/22987140/73457486-03f6e180-4374-11ea-8153-61c4f45b0ab1.png)

I can not find any other edit button

**Comment by Blatzheim** [comment]
This issue has been deprecated as of the discussion with @simonstadlinger today.
