### ISSUE TITLE
Questions get submitted when pressing enter

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#245]
It is currenlty impossible to add linebreaks to questions. This should be possible again!

**Comment by PaulBrachmann** [comment]
This is the intended behavior. (It's not a bug, it's ...)

We do not expect longer questions during a lecture and currently, there are no plans for a structured text answer system outside of them. The system should be kept as simple and as fast as possible. Thus, enter to send was chosen.
