### ISSUE TITLE
Profile Page and Login/signUp is broken

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#270]
Steps to reproduce:
1. (Remove existing databases)
2. `rails db:seed`
3. Try to login with seed data

If you are already signed in, try viewing your profile page

## http://localhost:3000/users/show
![image](https://user-images.githubusercontent.com/22987140/73082746-4c248880-3eca-11ea-88c2-f74272ec5450.png)

## SignUp:
![image](https://user-images.githubusercontent.com/22987140/73083068-cfde7500-3eca-11ea-8b59-d9feeb570a53.png)

**Comment by adrianjost** [comment]
Seems to be introduced with https://github.com/hpi-swt2/lecture-portal/pull/227/files

**Comment by adrianjost** [comment]
@LucPrestin @ma-ro

**Comment by MartinBuessemeyer** [comment]
https://hpi-lectureportal-dev.herokuapp.com/
works for me and I could create a user as normal

**Comment by MartinBuessemeyer** [comment]
https://hpi-lectureportal-dev.herokuapp.com/users/show seems to work as well
![image](https://user-images.githubusercontent.com/39387258/73087745-43848000-3ed3-11ea-955f-647037ad1009.png)

**Comment by MartinBuessemeyer** [comment]
OK clicking that button results in an error.

**Comment by essal0815** [comment]
@MartinBuessemeyer which button do you mean?
PR is merged but, can you proof that your error is fixed as well? If not please reopen the issue.

**Comment by MartinBuessemeyer** [comment]
I mean the subscribe button

**Comment by MartinBuessemeyer** [comment]
@essal0815 the link: https://hpi-lectureportal-dev.herokuapp.com/users/show does not work any more. Therefore I think we should not care about it?
