### ISSUE TITLE
Add "no ... added yet" to applicable places around the platform

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#284]
**AC**:
Lectures and students view:

- [x] - Course Dashboard: "No materials added to course yet" **in each tab** of file section if no file is added yet, as it can be seen in the mock.

- [x] Lecture Dashboard: "No questions asked yet" in dashboard tab and questions tab as it can be seen in the mock, if no question has been asked yet.

- [x]  Lecture Dashboard: "No materials added to lecture yet" in dashboard tab materials section, as it can be seen in the mock, if no files are added to the lecture yet.

- [x]  The "Files" Heading in the course dashboard says "Materials"

_Hint_:
https://www.figma.com/file/6yo4FXp2lLtE4uZvI0lsFr/Paper-Prototype?node-id=0%3A1

**Comment by phoeinx** [comment]
Proposal: Einheitliches "No material added yet" anstelle von lokalisiertes e.g."No material added to course yet"

**Comment by simonstadlinger** [comment]
The "Files" Heading in the course dashboard does not yet say "Materials" @phoeinx @jeriox
