### ISSUE TITLE
Poll responses and polls shouldn't reorder unless explicitly reordered by the lecturer

### ISSUE THREAD

**Issue by ADimeo** [hpi-swt2/lecture-portal#298]
Expected behaviour:
The answers to a poll should always be sorted exclusively in the order they were first created, top to bottom.

Current behaviour:
On the heroku dev order of items changes as people vote.
Direction change does not follow a clear pattern.

Reproduce:
Go to the dev deployment, vote in an active poll.
Reproduced across different devices, different users, different lectures and different polls.

NOTE: The same is true for polls themselves. They reorder based on "active" and "inactive". If you find out what causes the original bug please try to fix that aswell, or make a good note and tell your PO to open a new issue.

NOTE: As of now we're unable to reproduce these bugs in a development environment
NOTE: It may be sensible to discuss this with Team PB, since they may have faced a comparable problem in the past

**Comment by grittaweisheit** [comment]
This seems to be because we do not sort the options, so the db just shuffles them sometimes...
