### ISSUE TITLE
Polls shouldn't crash if deleted after being voted on

### ISSUE THREAD

**Issue by ADimeo** [hpi-swt2/lecture-portal#300]
Expected behaviour
Ruby doesn't crash when editing or modifyuing the poll after it was voted in

Current behaviour:
Ruby returns a  500(crash) when editing or modifyuing the poll after it was voted on.

Steps to reproduce:
1. As a lecturer, create a Poll
2. As a student, vote on that Poll
3. As a lecturer, try to modify or delete the poll
The application will now return a 500 error.

NOTE: As of now, not reproducible on locally hosted instance

**Comment by grittaweisheit** [comment]
This seems to fail because the foreign key constraint on answers is violated by deleting the polls poll_options
