### ISSUE TITLE
As a lecturer, I can access a lecture after it ended. (Estimation 3)

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#32]
**FROM THE LECTURERS VIEW**

- Ending a lecture adds the option "review" next to it in the [lectures list of lectures](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=0%3A1)

- Clicking on "review" takes the lecturer to the lectures dashboard

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by essal0815** [comment]
End Mode out of scope of this story (Only review view)
