### ISSUE TITLE
As a customer, I don’t want every user to be able to become a lecturer at any time

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#326]
DEP: None

AC:

(In the registration form:)
- [ ] The "is student" property is removed
- [ ] Instead, a field with the title "To become a lecturer, please enter the secret code" is presented
- [ ] The operator of the site is able to hard code a specific code into the application (A String)
- [ ] If a user enters this exact code into the previous mentioned new field, the newly created account will be a Lectures account. If the codes don't match (or the field is left empty) a student account will be created.

Edit account view:
- [ ] In the "Edit Account/Profile"-Section, the isStudent status can not be changed anymore.

_Hint: Because we don't have enough time, creating an entire admin role will not be considered. The basic idea is really just to have a hard coded code that a lecture can enter upon registration._

**Comment by WorldofJARcraft** [comment]
I will read the secret code from an environment variable, so the admin rather than the programmer can set it,.
