### ISSUE TITLE
Restyle "Delete Course" & "Unenroll"-Button

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#331]
“Destructive Action Buttons” (Delete Course & Leave Lecture) should all look like the "Delete File"-Button in the Materials Section.

**Comment by Blatzheim** [comment]
Changes not found in dev

**Comment by WorldofJARcraft** [comment]
Is merged now.

**Comment by Blatzheim** [comment]
See @essal0815 comments in PR
