### ISSUE TITLE
[ 5 ] As a lecturer, I want to see a view with tabs of the lecture I currently hold, so that I can quickly access all relevant information from a single page.

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swt2/lecture-portal#35]
**AC**:
- Integrated view contains empty tabbed views for questions, polls, feedback, settings)
- View can only be accessed by the lecturer that started the lecture. [tbd] 
- No page refresh, when switching tabs.

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by adrianjost** [comment]
![image](https://user-images.githubusercontent.com/22987140/69724807-ef506000-111c-11ea-93d5-2e626db60dbc.png)

**Comment by adrianjost** [comment]
Ne coole Tab Component die einfach einzubinden sein sollte:
https://www.webcomponents.org/element/vaadin/vaadin-tabs/demo/demo/index.html
Ansonsten hat Bootstrap auch schon was:
https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp
