### ISSUE TITLE
Courses should be able to be deleted, even when they contain archived lectures.

### ISSUE THREAD

**Issue by WorldofJARcraft** [hpi-swt2/lecture-portal#370]

**Comment by Blatzheim** [comment]
Does not seem to work

**Comment by essal0815** [comment]
Cant reproduce the bug. Deleted courses with several lectures, as well archived ones.
Further this was opened as a bug, so in theory does not require PO review?!

I used the dev heroku instance and local instance on both the same behaviour. Maybe Herouku was not updated, when you tried?! There was the building issue.

@Blatzheim I will move this issue to done, but feel free to reopen if needed :)
