### ISSUE TITLE
As a lecturer, I can end a lecture I have previously started (Estimation 1)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#38]
**FROM THE LECTURERS VIEW**

- Clicking on "end lecture" in the lecture view / dashboard ends the lecture

- Ending a lecture removes it from the [list of currently active lectures in the student view](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=36%3A216&scaling=min-zoom) and removes the option "view" from the [lecturers list of lectures
](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=0%3A1)

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by WorldofJARcraft** [comment]
Implemented in branch feature/#40-starting-lectures.

**Comment by essal0815** [comment]
The lecture shall not be restartable.
