### ISSUE TITLE
As a lecturer, I can start lecture that is in my "My lectures" list and has not been started yet (Estimation 8)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#40]
**FROM THE LECTURERS VIEW**

- A lecture that has not been started has the buttons "start" next to it in the ["My lectures" list ](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=32%3A14&scaling=min-zoom)

- Clicking on "Start" next to the lecture in the "My lectures" list will start the associated lecture

- Starting a lecture will add it to the [list of currently active lectures in the student view](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=36%3A216&scaling=min-zoom)

- After starting the lecture, the lecturer is presented with the dashboard view (tbd) of the newly started lecture

- Once a lecture is running, the lectures list of lectures no longer displays the options "start", but the option ["view", next to it](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=32%3A14&scaling=min-zoom), which will take the lecturer directly to the lecture's dashboard

- Nobody else but the lecturer that started the lecture can access the lecturer’s view (dashboard)

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by WorldofJARcraft** [comment]
Waiting to be able to link lecturer to lecture.
