### ISSUE TITLE
As a lecturer, I can edit the lectures settings (e.g. Title, Summary etc.) before and after i have started it (Estimation 3)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#45]
- A lecture that has not been started has the button "edit" next to it in the ["My lectures" list ](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=32%3A14&scaling=min-zoom)

- Clicking on "Edit" next to the lecture in the "My lectures" list will present the user with a separate edit view (tbd), from which he can only go back to the "My lectures" list

- Once a lecture is running, switching to the ["Settings" Tab](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=20%3A89&scaling=min-zoom) will present and provide the option to change Title, Description and wether the lecturer wants to include Questions and/or polls for this lecture

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by adrianjost** [comment]
waiting for #107
