### ISSUE TITLE
As a student, i can leave a lecture i have previously joined (Estimation 3)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#47]
**FROM THE STUDENT VIEW**

- Clicking on "leave lecture" (dashboard / lecture view, upper right corner), will take the student back to the list of all running lectures

- Clicking on "leave lecture" (dashboard / lecture view, upper right corner), will remove the student from the lectures list of students

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by adrianjost** [comment]
- [ ] Move Button into Tabbar

**Comment by adrianjost** [comment]
waiting for #119
