### ISSUE TITLE
As a Student, i want to have a view of all currently active lectures (Estimation 5)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#48]
**FROM THE STUDENT VIEW**

- A "[current lecture's page"](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=36%3A216&scaling=min-zoom) exists, from which a student will later be able to join a lecture by clicking on "join" 

- The page displays a list of all currently active lectures

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

**Comment by adrianjost** [comment]
Work is done at: https://github.com/hpi-swt2/lecture-portal/tree/feature/%2322-lecturer-create-new-lecture
