### ISSUE TITLE
Dashboard mit wichtigsten Infos designen

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#51]
> Diese Seite dient als "Hier ist alles auf einen Blick, wenn du mehr brauchst, schau in die Reiter"-Seite

# Lecturer-Dashboard-Tab:
- [ ] Fragen und die Info
# Student-Dashboard-Tab:
- [ ] Fragen, Info und ein Link zu einer ggf. aktiven poll.

Meine (@adrianjost) gedanken dazu:
- [ ] Lecturer view
  - [ ] open, most voted questions
  - [ ] button to create a poll
- [ ] Student view
  - [ ] open poll
  - [ ] open, most voted questions
  - [ ] create a question button

**Comment by Blatzheim** [comment]
Sieht soweit super aus!

@adrianjost
Danke für deine zusätzlichen Ideen.

Der Punkt _"Link zu einer gegebenenfalls aktiven Poll"_ (Student View -> "Open Poll") ist durchaus Sinnvoll. Hier könnt ihr euch am Style von Notifications orientieren, so dass eine Anzeige zu einem Poll auftaucht, wenn er läuft und danach wieder verschwindet.

Genauso verstehe ich deinen Gedanken zum Button "create poll" _im Dashboards des Lecturers_ und die Option "open poll" _im Dashboard des Students_.

Beide zuletzt erwähnten Optionen _stellen für mich jedoch das Konzept der Reiter, das wir im aktuellen Entwurf nutzen, infrage_. Sie würden den Poll-Reiter ja praktisch redundant machen, oder?
Generell erachte ich das Konzept von Reitern als Sinnvoll, kann aber auch verstehen, wenn man (z.B. in einer mobilen Version) lieber ohne sie Fahren will.
Was sind deine Gedanken dazu?


Aus diesem Grund werde ich alle unten folgende Punkte noch mit allen PO's diskutieren.

@adrianjost Es wäre schön, wenn bis dahin an allem anderen gearbeitet wird.
Konkret heist das aus meiner Sicht alles, bis auf die Option "create Poll" im Lecturer view und die Option "open Poll" im Student view.
Der Link zu einer Umfrage ist in jedem Fall Sinnvoll!

**Comment by Blatzheim** [comment]
@PaulBrachmann @simonstadlinger @ADimeo
Folgende Punkte stellen sich aus den Vorschlägen des Designteams zur Diskussion:

### Wie sinnvoll sind Reiter noch?
In einer Mobilen Version könnten Reiter zu Sperrig sein. Wollen wir das Konzept weiter verfolgen oder mit der Einführung eines Dashboards darauf verzichten? Was wäre unsere Alternative?

### "Link zu einer gegebenenfalls aktiven Poll" (Angenommen wir bleiben bei Reitern!)
Entweder, der Reiter "Poll" ist durchgehend offen, oder er öffnet sich erst, wenn man auf besagten Link klickt. Ich präferiere ersteres. In der zweiten Variante wäre gegebenenfalls schön, wenn ein aktiver Poll am Reiter erkennbar ist. Z.b. durch eine Art Notification Badge.

### "Aktiver Poll im Student Dashboard"
Würde aus meiner Sicht die UI zu sehr bloaten - besonders wenn wir mal über eine mobile Version nachdenken. Hierbei würde ich dann wie bereits bestehend, auf Reiter, oder eine Alternative zu diesen zurückgreifen.
D'accord?

### "Create Poll im Lecturer Dashboard"
Scheint mir in jeder Sicht sinnvoll um den Workflow des Lecturers zu beschleunigen. Hierfür könnte ich mir eine Art Aktionsspalte im Dashboard des Lecturers vorstellen, die wir in Zukunft auch mit weiteren Shortcuts zu wichtigen Features füllen könnten.
Was haltet ihr davon?

**Comment by adrianjost** [comment]
@Blatzheim Für mobil wollten wir auch bei Tabs bleiben. Ist gerade mobil auch ein gängiges Bedienkonzept. Gerade wenn die Tabs horizontal scrollen können. Das Dashboard hatten wir beim ursprünglichen Design nicht bedacht. Generell verstehen wir es aber als eine Art Übersicht mit Quicklinks. Der create Poll Button würde beispielsweise direkt in den Poll Tab wechseln und das erste Input fokussieren, sodass der Nutzer direkt lostippen kann.

**Comment by adrianjost** [comment]
Student View:
![image](https://user-images.githubusercontent.com/22987140/69731256-dc905800-1129-11ea-81e2-0be5cec270b7.png)

Lecture View:
genauso, aber nur updates vom typ "question"

Neue Updates werden immer links eingefügt, wenn zeile voll wird horizontal scrolling verwendet.
Klick Actions sind noch nicht definiert
