### ISSUE TITLE
PO Feedback einarbeiten - Questions

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#52]
# Lecturer-Questions-Tab

- [x] Resolved Questions sollten optisch passiver sein, als aktive. Der grüne Schriftzug hebt aktuell die resolved Questions eher hervor.

# Student-Question-Tab:
- [ ] Resolved Questions sollten optisch passiver sein, als aktive. Der grüne Schriftzug hebt aktuell die resolved Questions eher hervor.
- ~Ein Student sollte das resolved nicht wegnehmen können, wenn der Lecturer das als resolved markiert hat, sondern eine anders Formulierte Frage stellen. Darum müssen wir uns also nicht kümmern.~ done

**Comment by Blatzheim** [comment]
Super! :)

**Comment by adrianjost** [comment]
![image](https://user-images.githubusercontent.com/22987140/69731416-2a0cc500-112a-11ea-9ff2-ffd957ec797a.png)
