### ISSUE TITLE
PO Feedback einarbeiten - Settings

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#53]
# Lecturer-Settings-Tab:
- [x] hier steht die Multiselectbox drin, die eigentlich für das Erstellen von Polls gedacht war. Meine Schuld, muss ich noch fixen. Edit: Done
- [ ] Aktuell lässt sich eine Lecture aus der "My lecture list" bearbeiten (edit), was den user direkt in den "Settings"-Reiter bringt, wodurch er dann wiederum in der Lecture fröhlich rumklicken kann. Undzwar ohne dass diese gestartet wurde.
Es wäre besser, wenn eine isolierte Edit-page, ähnlich der, die bei der Erstellung gezeigt wird.

**Comment by Blatzheim** [comment]
Besser hätte ich es selbst nicht formulieren können. *hust* 😂

**Comment by lpfennigschmidt** [comment]
Ich würde an dieser Stelle den Prototypen so lassen wie er ist, die Anmerkung ist natürlich berechtigt und sollte im richtigen Produkt berücksichtigt werden, dass da der Workflow anders funktioniert und man nur zur Lecture-Overview mit den Tabs kommt, wenn sie vorher gestartet wurde.
