### ISSUE TITLE
PO Feedback einarbeiten - Polls

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#54]
# Lecturer-Poll-Tab:
- [x] Sollte man als Lecturer im MVP nur die Anzahl der Antwortmöglichkeiten auswählen können; nicht aber schon Antwortwort-Strings spezifizieren
- [x] Für das MVP ist noch kein live Update vorgesehen. Vielmehr soll der Lecturer einen Button "Close poll and show results" bekommen, den er nach dem Erstellen der Poll drücken kann und der dann zu den Aggregierten Ergebnissen umleitet. Quasi das TI-Modell mit "Kommt zum Ende, ich schließe die Frage"
# Student-Poll-Tab:
- [x] Im Mockup fehlt noch eine Seite für die Students, für den Fall, dass keine Poll aktiv ist.

**Comment by Blatzheim** [comment]
Past!
