### ISSUE TITLE
PO Feedback einarbeiten - Feedback

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#55]
# Lecturer-Feedback-Tab:
- [x] Soll noch in den Mockup

# Student-Feedback-Tab:
- [ ] Soll noch in den Mockup

**Comment by Blatzheim** [comment]
Hier bitte noch konkretere Vorschläge, bzw. Prototypen.

**Comment by adrianjost** [comment]
Student View:
![image](https://user-images.githubusercontent.com/22987140/69731463-3db82b80-112a-11ea-8ed8-0a18ccf5d8c2.png)

Lecturer View:
![image](https://user-images.githubusercontent.com/22987140/69731509-4f99ce80-112a-11ea-8cfd-0696ea0376e7.png)
