### ISSUE TITLE
PO Feedback einarbeiten - Overview

### ISSUE THREAD

**Issue by adrianjost** [hpi-swt2/lecture-portal#56]
- [x] Wird die Option "view" noch nicht weiter spezifiziert. Hier sollte man zwischen einer aktiven und einer beedneten Lecture unterscheiden. Ist die Lecture aktiv, soll "view" einen ins Dashbord bringen; während, wenn die Lecture beendet wurde, eine option "Review" beispielsweise  ein ausgegrautes Dashboard zeigen sollte, welches nicht mehr modifiziert werden kann (da die lecture beendet ist).

**Comment by Blatzheim** [comment]
@adrianjost Hier wäre wieder ein Konkreter Vorschlag im vgl. zu "beispielsweise ein ausgegrautes Dashboard" angebracht. Was genau soll passieren, gibt es noch bessere Möglichkeiten?

 Am Besten wäre natürlich eine, die möglichst leicht implementierbar und trotzdem gut Verständlich ist.
