### ISSUE TITLE
As a lecturer, or as a student, i want to be able to upload files that i can then associate with a lecture or a course. (Estimation 13)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#83]
Dependencies: NONE

Acceptance Criteria:
- A "File" DB-Scheme exists
-  In the scheme, a file can be associated with a lecture, or a course

_Hint:
Courses will be implemented in this sprint, by Team "Überlapsch". However, much like the schemes developed in Sprint 1, this Scheme does not depend on other implementation. It should only provide a basic function to upload a file dot the DB, and associate it either with a lecture, or a course (a file can belong to a course or a lecture, but a lecture always belongs to a course)._

**Comment by essal0815** [comment]
DB-sheme minimum: Filename, Datatype, BinaryArray
Filename duplicates shall be possible

Backend logic for file upload in scope, but no view.

authorization is out of scope of this ticket

Course or lecture is exclusiv (if lecture is selected course is implicitly given)

**Comment by adrianjost** [comment]
course müssen noch files kennen lernen
