### ISSUE TITLE
As a lecturer, or as a student, i want to clarify what kind of file i will upload. (Estimation 3)

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#84]
Dependencies: #83

AC:
- [ ] In the DB scheme, a file can be classified as ONE of the following: Notes, Summary, Lecture Slides, Lecture Marerial

- [ ] The scheme should support the future addition of other classifications

**Comment by essal0815** [comment]
Currently shall only be this 4 categories, but shall be adoptable for new categories. At least static adoption shall be possible easyly.

One File has one category
